include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    document_ignores: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    eol_at_end_of_file: false
     # buang balik nanti
    prefer_const_constructors: false 
    prefer_const_literals_to_create_immutables: false