name: ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  amicons: ^1.0.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mobile_scanner: ^7.0.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  roggle: ^0.4.2+1
  supabase_flutter: ^2.9.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: false
