name: ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  amicons: ^1.0.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  june: ^1.0.0+1
  mobile_scanner: ^7.0.0
  roggle: ^0.4.2+1
  supabase_flutter: ^2.9.0
  swipeable_page_route: ^0.4.7

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: false
